/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mupomat.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mupomat.model.Operater;

/**
 *
 * @author SrKy
 */
public class Izbornik extends javax.swing.JFrame implements Runnable {

    private Operater operater;
    private Thread runner;

    /**
     * Creates new form Izbornik
     *
     * @param operater
     */
    public Izbornik(Operater operater) {
        initComponents();
        datum();
        this.operater = operater;
        setTitle("MUPomat: " + operater.getImePrezime() + " " + "(Administrator)");
        centrirajZaslon();
        dodajIkonu();
        start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOperateri = new javax.swing.JButton();
        btnPolicijskeUprave = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        lblDatum = new javax.swing.JLabel();
        lblSat = new javax.swing.JLabel();
        btnGradovi = new javax.swing.JButton();
        btnPolicijskePostaje = new javax.swing.JButton();
        btnAutomati = new javax.swing.JButton();
        btnDokumenti = new javax.swing.JButton();
        btnKorisnici = new javax.swing.JButton();
        btnOdjaviteSe = new javax.swing.JButton();
        btnIzlaz = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOperateri = new javax.swing.JMenuItem();
        menuPolicijskeUprave = new javax.swing.JMenuItem();
        menuGradovi = new javax.swing.JMenuItem();
        menuPolicijskePostaje = new javax.swing.JMenuItem();
        menuAutomati = new javax.swing.JMenuItem();
        menuDokumenti = new javax.swing.JMenuItem();
        menuKorisnici = new javax.swing.JMenuItem();
        menuIzlaz = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOperateri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/usermenuicon.png"))); // NOI18N
        btnOperateri.setText("ADMINISTRATORI");
        btnOperateri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOperateri.setPreferredSize(new java.awt.Dimension(80, 30));
        btnOperateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperateriActionPerformed(evt);
            }
        });

        btnPolicijskeUprave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/pumenuicon.png"))); // NOI18N
        btnPolicijskeUprave.setText("POLICIJSKE UPRAVE");
        btnPolicijskeUprave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPolicijskeUprave.setPreferredSize(new java.awt.Dimension(80, 30));
        btnPolicijskeUprave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicijskeUpraveActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        lblDatum.setText("datum");
        jToolBar1.add(lblDatum);

        lblSat.setText("vrijeme");
        jToolBar1.add(lblSat);

        btnGradovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/gradmenuicon.png"))); // NOI18N
        btnGradovi.setText("GRADOVI");
        btnGradovi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGradovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradoviActionPerformed(evt);
            }
        });

        btnPolicijskePostaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/ppmenuicon.png"))); // NOI18N
        btnPolicijskePostaje.setText("POLICIJSKE POSTAJE");
        btnPolicijskePostaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPolicijskePostaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicijskePostajeActionPerformed(evt);
            }
        });

        btnAutomati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/automatmenuicon.png"))); // NOI18N
        btnAutomati.setText("AUTOMATI");
        btnAutomati.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAutomati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomatiActionPerformed(evt);
            }
        });

        btnDokumenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/dokumentikona.png"))); // NOI18N
        btnDokumenti.setText("DOKUMENTI");
        btnDokumenti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDokumenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokumentiActionPerformed(evt);
            }
        });

        btnKorisnici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/korisniciikona.png"))); // NOI18N
        btnKorisnici.setText("KORISNICI");
        btnKorisnici.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKorisnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKorisniciActionPerformed(evt);
            }
        });

        btnOdjaviteSe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/odjaviteseikona.png"))); // NOI18N
        btnOdjaviteSe.setText("ODJAVITE SE");
        btnOdjaviteSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviteSeActionPerformed(evt);
            }
        });

        btnIzlaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/izlazikona.png"))); // NOI18N
        btnIzlaz.setText("IZLAZ");
        btnIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzlazActionPerformed(evt);
            }
        });

        jMenu1.setText("Programi");

        menuOperateri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuOperateri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/usermenuicon.png"))); // NOI18N
        menuOperateri.setText("Administratori");
        menuOperateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOperateriActionPerformed(evt);
            }
        });
        jMenu1.add(menuOperateri);

        menuPolicijskeUprave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuPolicijskeUprave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/pumenuicon.png"))); // NOI18N
        menuPolicijskeUprave.setText("Policijske uprave");
        menuPolicijskeUprave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPolicijskeUpraveActionPerformed(evt);
            }
        });
        jMenu1.add(menuPolicijskeUprave);

        menuGradovi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuGradovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/gradmenuicon.png"))); // NOI18N
        menuGradovi.setText("Gradovi");
        menuGradovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGradoviActionPerformed(evt);
            }
        });
        jMenu1.add(menuGradovi);

        menuPolicijskePostaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuPolicijskePostaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/ppmenuicon.png"))); // NOI18N
        menuPolicijskePostaje.setText("Policijske postaje");
        menuPolicijskePostaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPolicijskePostajeActionPerformed(evt);
            }
        });
        jMenu1.add(menuPolicijskePostaje);

        menuAutomati.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuAutomati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/automatmenuicon.png"))); // NOI18N
        menuAutomati.setText("Automati");
        jMenu1.add(menuAutomati);

        menuDokumenti.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuDokumenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/dokumentikona.png"))); // NOI18N
        menuDokumenti.setText("Dokumenti");
        menuDokumenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDokumentiActionPerformed(evt);
            }
        });
        jMenu1.add(menuDokumenti);

        menuKorisnici.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuKorisnici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/korisniciikona.png"))); // NOI18N
        menuKorisnici.setText("Korisnici");
        menuKorisnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKorisniciActionPerformed(evt);
            }
        });
        jMenu1.add(menuKorisnici);

        menuIzlaz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuIzlaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/exitmenuicon.png"))); // NOI18N
        menuIzlaz.setText("Izlaz");
        menuIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIzlazActionPerformed(evt);
            }
        });
        jMenu1.add(menuIzlaz);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pomoćno");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPolicijskeUprave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGradovi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPolicijskePostaje, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnDokumenti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnAutomati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOperateri, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzlaz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOdjaviteSe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPolicijskeUprave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOperateri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGradovi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPolicijskePostaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutomati, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDokumenti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnOdjaviteSe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzlaz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOperateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOperateriActionPerformed
        otvaranjeProgramaOperateri();
    }//GEN-LAST:event_menuOperateriActionPerformed

    private void menuPolicijskeUpraveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPolicijskeUpraveActionPerformed
        otvaranjeProgramaPolicijskeUprave();
    }//GEN-LAST:event_menuPolicijskeUpraveActionPerformed

    private void menuDokumentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDokumentiActionPerformed
        otvaranjeProgramaDokumenti();
    }//GEN-LAST:event_menuDokumentiActionPerformed

    private void menuIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIzlazActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuIzlazActionPerformed

    private void btnPolicijskeUpraveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicijskeUpraveActionPerformed
        otvaranjeProgramaPolicijskeUprave();
    }//GEN-LAST:event_btnPolicijskeUpraveActionPerformed

    private void btnOperateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperateriActionPerformed

        otvaranjeProgramaOperateri();
    }//GEN-LAST:event_btnOperateriActionPerformed

    private void btnGradoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradoviActionPerformed
        otvaranjeProgramaGradovi();
    }//GEN-LAST:event_btnGradoviActionPerformed

    private void menuGradoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGradoviActionPerformed
        otvaranjeProgramaGradovi();
    }//GEN-LAST:event_menuGradoviActionPerformed

    private void btnKorisniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKorisniciActionPerformed
        otvaranjeProgramaKorisnici();
    }//GEN-LAST:event_btnKorisniciActionPerformed

    private void menuKorisniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKorisniciActionPerformed
        otvaranjeProgramaKorisnici();
    }//GEN-LAST:event_menuKorisniciActionPerformed

    private void btnPolicijskePostajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicijskePostajeActionPerformed
        otvaranjeProgramaPolicijskePostaje();
    }//GEN-LAST:event_btnPolicijskePostajeActionPerformed

    private void menuPolicijskePostajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPolicijskePostajeActionPerformed
        otvaranjeProgramaPolicijskePostaje();
    }//GEN-LAST:event_menuPolicijskePostajeActionPerformed

    private void btnDokumentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokumentiActionPerformed
        otvaranjeProgramaDokumenti();
    }//GEN-LAST:event_btnDokumentiActionPerformed

    private void btnAutomatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomatiActionPerformed
        otvaranjeProgramaAutomati();
    }//GEN-LAST:event_btnAutomatiActionPerformed

    private void btnOdjaviteSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviteSeActionPerformed

        Object[] options = {"Odjavi me",
            "Ostani",};
        int rez = JOptionPane.showOptionDialog(rootPane,//parent container of JOptionPane
                "Želite se odjaviti?",
                "MUPomat: Odjava",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,//do not use a custom Icon
                options,//the titles of buttons
                null);//default button title
        if (rez == JOptionPane.YES_OPTION) {
            this.dispose();
            new PrijavaKorisnika().setVisible(true);
        }
    }//GEN-LAST:event_btnOdjaviteSeActionPerformed

    private void btnIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlazActionPerformed

        Object[] options = {"Izađi",
            "Ostani",};
        int rez = JOptionPane.showOptionDialog(rootPane,//parent container of JOptionPane
                "Želite izaći iz programa?",
                "MUPomat: Izlaz",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,//do not use a custom Icon
                options,//the titles of buttons
                null);//default button title
        if (rez == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnIzlazActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomati;
    private javax.swing.JButton btnDokumenti;
    private javax.swing.JButton btnGradovi;
    private javax.swing.JButton btnIzlaz;
    private javax.swing.JButton btnKorisnici;
    private javax.swing.JButton btnOdjaviteSe;
    private javax.swing.JButton btnOperateri;
    private javax.swing.JButton btnPolicijskePostaje;
    private javax.swing.JButton btnPolicijskeUprave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblSat;
    private javax.swing.JMenuItem menuAutomati;
    private javax.swing.JMenuItem menuDokumenti;
    private javax.swing.JMenuItem menuGradovi;
    private javax.swing.JMenuItem menuIzlaz;
    private javax.swing.JMenuItem menuKorisnici;
    private javax.swing.JMenuItem menuOperateri;
    private javax.swing.JMenuItem menuPolicijskePostaje;
    private javax.swing.JMenuItem menuPolicijskeUprave;
    // End of variables declaration//GEN-END:variables

    private void centrirajZaslon() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        this.setResizable(false);
    }

    private void dodajIkonu() {
        this.setIconImage(new ImageIcon(getClass()
                .getResource("/mupomat" + "/pictures" + "/m.png")).getImage());
    }

    private void otvaranjeProgramaOperateri() {

        new Operateri().setVisible(true);

    }

    private void otvaranjeProgramaPolicijskeUprave() {
        new PolicijskeUprave(operater).setVisible(true);
    }

    private void otvaranjeProgramaGradovi() {
        new Gradovi(operater).setVisible(true);
    }

    private void otvaranjeProgramaKorisnici() {
        new Korisnici(operater).setVisible(true);
    }

    private void otvaranjeProgramaPolicijskePostaje() {
        new PolicijskePostaje(operater).setVisible(true);
    }

    private void otvaranjeProgramaDokumenti() {
        new Dokumenti(operater).setVisible(true);
    }

    private void otvaranjeProgramaAutomati() {
        new Automati(operater).setVisible(true);
    }

    private void datum() {

        Calendar cal = new GregorianCalendar();
        int dan = cal.get(Calendar.DAY_OF_MONTH);
        int mjesec = cal.get(Calendar.MONTH) + 1;
        int godina = cal.get(Calendar.YEAR);

        String dan1 = Integer.toString(dan);
        if (dan < 10) {
            dan1 = "0" + dan;
        }

        String mjesec1 = Integer.toString(mjesec);
        if (mjesec < 10) {
            mjesec1 = "0" + mjesec;
        }

        String[] daniutjednu = new String[]{"Nedjelja", "Ponedjeljak", "Utorak", "Srijeda", "Četvrtak",
            "Petak", "Subota"};

        lblDatum.setText("  " + daniutjednu[cal.get(Calendar.DAY_OF_WEEK) - 1] + ", " + dan1 + "." + mjesec1 + "." + godina + "." + " ");

    }

    public String timeNow() {
        Calendar now = Calendar.getInstance();
        int hrs = now.get(Calendar.HOUR_OF_DAY);
        int min = now.get(Calendar.MINUTE);
        int sec = now.get(Calendar.SECOND);

        String time = zero(hrs) + ":" + zero(min) + ":" + zero(sec);

        return time;

    }

    public String zero(int num) {
        String number = (num < 10) ? ("0" + num) : ("" + num);
        return number;                                    //Add leading zero if needed

    }

    public void start() {
        if (runner == null) {
            runner = new Thread(this);
        }
        runner.start();
        //method to start thread
    }

    public void run() {
        while (runner == Thread.currentThread()) {
            lblSat.setText(timeNow());
            repaint();
            //define thread task
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                System.out.println("Thread failed");
            }

        }
    }

}
