/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mupomat.view;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import mupomat.utility.LongLatService;

/**
 *
 * @author SrKy
 */
public class Mape extends javax.swing.JFrame {

   
    private Mupomat mupomat;
    public LongLatService longLatService;
    private String lon;
    private String lat;
    

    /**
     * Creates new form Mape
     */
    public Mape(Mupomat mupomat, String lon, String lat) {
        initComponents();
        this.mupomat = mupomat;
        this.lon = lon;
        this.lat = lat;
        
        this.setIconImage(new ImageIcon(getClass()
                .getResource("/mupomat" + "/pictures" + "/m.png")).getImage());
        setTitle("MUPomat: Mapa");
        this.setResizable(false);
        kreirajMapu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMapa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMapa.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMapa;
    // End of variables declaration//GEN-END:variables

    private void kreirajMapu() {
        try {
             System.out.println("http://maps.googleapis.com/maps/api/staticmap?center="+mupomat.adresa+"&zoom=15&size=300x300&maptype=roadmap&&markers=color:blue%7Clabel:M%7C"+lat+","+lon+"sensor=false");
         
            BufferedImage mapa = ImageIO.read(new URL("http://maps.googleapis.com/maps/api/staticmap?center="+mupomat.adresa+"&zoom=15&size=300x300&maptype=roadmap&markers=color:blue%7Clabel:M%7C"+lat+","+lon+"&sensor=false"));
            //iza roadmap zaljepi ovo &markers=color:blue%7Clabel:M%7C45.553627,18.684498
            // &markers=color:blue%7Clabel:M%7C"+longLatService.strLatitude+","+longLatService.strLongtitude+"
              lblMapa.setIcon(new ImageIcon(mapa));
        } catch (IOException ex) {
            Logger.getLogger(Mape.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
