/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mupomat.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mupomat.controller.ObradaPolicijskaUprava;
import mupomat.model.Operater;
import mupomat.model.PolicijskaUprava;
import mupomat.utility.Kontrola;

/**
 *
 * @author SrKy
 */
public class PolicijskeUprave extends javax.swing.JFrame {

    private Pattern pattern;
    private Matcher matcher;
    private ObradaPolicijskaUprava obradaPolicijskaUprava;
    private PolicijskaUprava policijskaUprava;
    private Operater operater;
    private ImageIcon ikona;

    /**
     * Creates new form PolicijskeUprave
     *
     * @param operater
     */
    public PolicijskeUprave(Operater operater) {
        initComponents();
        setTitle("MUPomat: Policijske uprave");
        ikona = new ImageIcon(getClass().getResource("/mupomat/pictures/balloonerror.png"));
        centrirajZaslon();
        dodajIkonu();
        obradaPolicijskaUprava = new ObradaPolicijskaUprava();
        this.operater = operater;
        trazi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUvjet = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNacelnik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSjediste = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtInternetStranica = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzlaz = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDatumUnosa = new javax.swing.JLabel();
        lblDatumPromjene = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPolicijskihUprava = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Traži policijsku upravu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        txtUvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUvjetKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUvjet, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o policijskoj upravi"));

        jLabel1.setText("Naziv");

        jLabel2.setText("Načelnik");

        jLabel3.setText("Sjedište");

        jLabel4.setText("Adresa");

        jLabel5.setText("Telefon");

        jLabel6.setText("Internet stranica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNaziv)
                    .addComponent(txtNacelnik)
                    .addComponent(txtSjediste)
                    .addComponent(txtAdresa)
                    .addComponent(txtTelefon)
                    .addComponent(txtInternetStranica))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNacelnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSjediste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInternetStranica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcije"));

        btnDodaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/dodajikona.png"))); // NOI18N
        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/promjeniikona.png"))); // NOI18N
        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/obrisiikona.png"))); // NOI18N
        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzlaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/izlazikona.png"))); // NOI18N
        btnIzlaz.setText("Izlaz");
        btnIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzlazActionPerformed(evt);
            }
        });

        btnPonisti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mupomat/pictures/ponistiikona.png"))); // NOI18N
        btnPonisti.setText("Poništi");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPromjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzlaz, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnPromjeni)
                    .addComponent(btnPonisti)
                    .addComponent(btnIzlaz)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datumi"));
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 79));

        jLabel8.setText("Datum unosa:");

        jLabel9.setText("Datum promjene:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatumUnosa)
                    .addComponent(lblDatumPromjene))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDatumUnosa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDatumPromjene))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Policijske uprave u bazi"));

        listaPolicijskihUprava.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPolicijskihUpravaValueChanged(evt);
            }
        });
        listaPolicijskihUprava.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaPolicijskihUpravaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listaPolicijskihUprava);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUvjetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUvjetKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            trazi();
        }
    }//GEN-LAST:event_txtUvjetKeyPressed

    private void listaPolicijskihUpravaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPolicijskihUpravaValueChanged

        if (evt.getValueIsAdjusting()) {
            return;
        }

        policijskaUprava = (PolicijskaUprava) listaPolicijskihUprava.getSelectedValue();

        if (policijskaUprava == null) {
            return;
        }

        SimpleDateFormat df = new SimpleDateFormat(Kontrola.FORMAT_DATUMA_VRIJEME);
        lblDatumUnosa.setText(df.format(policijskaUprava.getDatumUnosa()));

        if (policijskaUprava.getDatumPromjene() != null) {
            lblDatumPromjene.setText(df.format(policijskaUprava.getDatumPromjene()));
        }

        txtNaziv.setText(policijskaUprava.getNaziv());
        txtNacelnik.setText(policijskaUprava.getNacelnik());
        txtSjediste.setText(policijskaUprava.getSjediste());
        txtAdresa.setText(policijskaUprava.getAdresa());
        txtTelefon.setText(policijskaUprava.getTelefon());
        txtInternetStranica.setText(policijskaUprava.getInternetstranica());


    }//GEN-LAST:event_listaPolicijskihUpravaValueChanged

    private void btnIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlazActionPerformed

        Object[] options = {"Izađi",
            "Ostani"};
        int rez = JOptionPane.showOptionDialog(rootPane,//parent container of JOptionPane
                "Jeste li sigurni da želite izaći iz policijskih uprava?",
                "Izlaz",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,//do not use a custom Icon
                options,//the titles of buttons
                null);//default button title
        if (rez == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnIzlazActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if (!kontrola()) {
            return;
        }

        policijskaUprava = new PolicijskaUprava();
        policijskaUprava.setNaziv(txtNaziv.getText());
        policijskaUprava.setNacelnik(txtNacelnik.getText());
        policijskaUprava.setSjediste(txtSjediste.getText());
        policijskaUprava.setAdresa(txtAdresa.getText());
        policijskaUprava.setTelefon(txtTelefon.getText());
        policijskaUprava.setInternetstranica(txtInternetStranica.getText());
        policijskaUprava.setOperater(operater);
        policijskaUprava = obradaPolicijskaUprava.dodajNovi(policijskaUprava);

        trazi();
        pocistiPolja();

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        if (policijskaUprava == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite policijsku upravu!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!kontrola()) {
            return;
        }

        policijskaUprava.setNaziv(txtNaziv.getText());
        policijskaUprava.setNacelnik(txtNacelnik.getText());
        policijskaUprava.setSjediste(txtSjediste.getText());
        policijskaUprava.setAdresa(txtAdresa.getText());
        policijskaUprava.setTelefon(txtTelefon.getText());
        policijskaUprava.setInternetstranica(txtInternetStranica.getText());
        policijskaUprava.setOperater(operater);
        obradaPolicijskaUprava.promjeniPostojeci(policijskaUprava);

        pocistiPolja();
        trazi();

    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (policijskaUprava == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite policijsku upravu!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object[] options = {"Da",
            "Ne",};
        int rez = JOptionPane.showOptionDialog(rootPane,//parent container of JOptionPane
                "Sigurno obrisati?",
                "Brisanje",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,//do not use a custom Icon
                options,//the titles of buttons
                null);//default button title
        if (rez == JOptionPane.YES_OPTION) {
            try {
                obradaPolicijskaUprava.obrisiPostojeci(policijskaUprava);
                trazi();
                pocistiPolja();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Policijska uprava se ne može obrisati jer je na nju prijavljen jedan ili više gradova!", "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        pocistiPolja();
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void listaPolicijskihUpravaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaPolicijskihUpravaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            btnObrisiActionPerformed(null);
        }
    }//GEN-LAST:event_listaPolicijskihUpravaKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzlaz;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumPromjene;
    private javax.swing.JLabel lblDatumUnosa;
    private javax.swing.JList listaPolicijskihUprava;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtInternetStranica;
    private javax.swing.JTextField txtNacelnik;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtSjediste;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables

    private void trazi() {
        List<PolicijskaUprava> lista = obradaPolicijskaUprava.dohvatiIzBaze(txtUvjet.getText().trim());
        DefaultListModel<PolicijskaUprava> m = new DefaultListModel<>();

        for (PolicijskaUprava policijskaUprava : lista) {
            m.addElement(policijskaUprava);
        }
        listaPolicijskihUprava.setModel(m);

    }

    private void centrirajZaslon() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        this.setResizable(false);

    }

    private void dodajIkonu() {
        this.setIconImage(new ImageIcon(getClass()
                .getResource("/mupomat" + "/pictures" + "/pumenuicon.png")).getImage());
    }

    private boolean kontrola() {

        if (!kontrolaNaziv()
                || !kontrolaNacelnik()
                || !kontrolaSjediste()
                || !kontrolaAdresa()
                || !kontrolaTelefon()
                || !kontrolaInternetStranica()) {
            return false;
        }

        return true;
    }

    private void pocistiPolja() {

        txtNaziv.setText("");
        txtNacelnik.setText("");
        txtSjediste.setText("");
        txtAdresa.setText("");
        txtTelefon.setText("");
        txtInternetStranica.setText("");

    }

    private boolean kontrolaNaziv() {
        pattern = Pattern.compile(Kontrola.NAZIV_POLICIJSKE_UPRAVE);
        matcher = pattern.matcher(txtNaziv.getText().trim());

        Kontrola.resetirajPoljeGreske(txtNaziv);
        if (!Kontrola.kontrolaPraznoPolje(txtNaziv.getText(), txtNaziv, "Ovo polje je obavezno! ", ikona)) {
            Kontrola.oznaciPoljeGreske(txtNaziv);
            return false;
        }
        if (!matcher.matches()) {
            Kontrola.kontrolaUnosa(txtNaziv, "<html>Netočan unos.<br>Dopušteno: [a-ž,A-Ž,-]<br>(min.6 max.30 znakova)</html> ", ikona);
            Kontrola.oznaciPoljeGreske(txtNaziv);
            return false;
        }

        return true;
    }

    private boolean kontrolaNacelnik() {
        pattern = Pattern.compile(Kontrola.IME_PREZIME_NACELNIKA);
        matcher = pattern.matcher(txtNacelnik.getText().trim());

        Kontrola.resetirajPoljeGreske(txtNacelnik);
        if (!Kontrola.kontrolaPraznoPolje(txtNacelnik.getText(), txtNacelnik, "Ovo polje je obavezno! ", ikona)) {
            Kontrola.oznaciPoljeGreske(txtNacelnik);
            return false;
        }
        if (!matcher.matches()) {
            Kontrola.kontrolaUnosa(txtNacelnik, "<html>Netočan unos.<br>Dopušteno: [a-ž,A-Ž,razmak]<br>(min.5 max.50 znakova)</html> ", ikona);
            Kontrola.oznaciPoljeGreske(txtNacelnik);
            return false;
        }

        return true;
    }

    private boolean kontrolaSjediste() {
        pattern = Pattern.compile(Kontrola.NAZIV_SJEDISTA);
        matcher = pattern.matcher(txtSjediste.getText().trim());

        Kontrola.resetirajPoljeGreske(txtSjediste);
        if (!Kontrola.kontrolaPraznoPolje(txtSjediste.getText(), txtSjediste, "Ovo polje je obavezno! ", ikona)) {
            Kontrola.oznaciPoljeGreske(txtSjediste);
            return false;
        }
        if (!matcher.matches()) {
            Kontrola.kontrolaUnosa(txtSjediste, "<html>Netočan unos.<br>Dopušteno: [a-ž,A-Ž,razmak]<br.(min.4 max.20 znakova)</html> ", ikona);
            Kontrola.oznaciPoljeGreske(txtSjediste);
            return false;
        }

        return true;
    }

    private boolean kontrolaAdresa() {
        pattern = Pattern.compile(Kontrola.ADRESA);
        matcher = pattern.matcher(txtAdresa.getText().trim());

        Kontrola.resetirajPoljeGreske(txtAdresa);
        if (!Kontrola.kontrolaPraznoPolje(txtAdresa.getText(), txtAdresa, "Ovo polje je obavezno! ", ikona)) {
            Kontrola.oznaciPoljeGreske(txtAdresa);
            return false;
        }
        if (!matcher.matches()) {
            Kontrola.kontrolaUnosa(txtAdresa, "<html>Netočan unos.<br>Dopušteno: [a-ž,A-Ž,0-9,.,razmak]<br>(min.6 max.50 znakova)</html> ", ikona);
            Kontrola.oznaciPoljeGreske(txtAdresa);
            return false;
        }

        return true;
    }

    private boolean kontrolaTelefon() {
        pattern = Pattern.compile(Kontrola.TELEFON);
        matcher = pattern.matcher(txtTelefon.getText().trim());

        Kontrola.resetirajPoljeGreske(txtTelefon);
        if (!Kontrola.kontrolaPraznoPolje(txtTelefon.getText(), txtTelefon, "Ovo polje je obavezno! ", ikona)) {
            Kontrola.oznaciPoljeGreske(txtTelefon);
            return false;
        }
        if (!matcher.matches()) {
            Kontrola.kontrolaUnosa(txtTelefon, "<html>Netočan unos.<br>Dopušteno: [0-9,/,-]<br.(min.10 max.11 znakova)<br>Primjer: 123/456-789</html> ", ikona);
            Kontrola.oznaciPoljeGreske(txtTelefon);
            return false;
        }

        return true;
    }

    private boolean kontrolaInternetStranica() {
        pattern = Pattern.compile(Kontrola.WEB_ADRESA);
        matcher = pattern.matcher(txtInternetStranica.getText().trim());

        Kontrola.resetirajPoljeGreske(txtInternetStranica);
        if (!Kontrola.kontrolaPraznoPolje(txtInternetStranica.getText(), txtInternetStranica, "Ovo polje je obavezno! ", ikona)) {
            Kontrola.oznaciPoljeGreske(txtInternetStranica);
            return false;
        }
        if (!matcher.matches()) {
            Kontrola.kontrolaUnosa(txtInternetStranica, "<html>Netočan unos.<br>Dopušteno: [a-z,.,-,@]<br>(min.11 max.50 znakova)<br>Primjer: www.naziv.hr</html> ", ikona);
            Kontrola.oznaciPoljeGreske(txtInternetStranica);
            return false;
        }

        return true;
    }

}
